### PR TITLE
support for tailwindv3

### LINKED ISSUE #9: Tailwind 3 support
Tailwind version 3 released yesterday: https://tailwindcss.com/blog/tailwindcss-v3

elm-tailwind-modules fails with:
```
(node:81442) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat 'generated in-memory'
    at Object.statSync (fs.js:1131:3)
    at trackModified (/Users/js/Documents/git/personal/elm-site-template/node_modules/tailwindcss/lib/lib/setupContextUtils.js:447:39)
    at Object.getContext (/Users/js/Documents/git/personal/elm-site-template/node_modules/tailwindcss/lib/lib/setupContextUtils.js:788:5)
    at /Users/js/Documents/git/personal/elm-site-template/node_modules/tailwindcss/lib/lib/setupTrackingContext.js:141:53
    at /Users/js/Documents/git/personal/elm-site-template/node_modules/tailwindcss/lib/processTailwindFeatures.js:37:11
    at plugins (/Users/js/Documents/git/personal/elm-site-template/node_modules/tailwindcss/lib/index.js:22:68)
    at LazyResult.runOnRoot (/Users/js/Documents/git/personal/elm-site-template/node_modules/postcss/lib/lazy-result.js:339:16)
    at LazyResult.runAsync (/Users/js/Documents/git/personal/elm-site-template/node_modules/postcss/lib/lazy-result.js:393:26)
    at LazyResult.async (/Users/js/Documents/git/personal/elm-site-template/node_modules/postcss/lib/lazy-result.js:221:30)
    at LazyResult.then (/Users/js/Documents/git/personal/elm-site-template/node_modules/postcss/lib/lazy-result.js:206:17)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:81442) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:81442) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### PR DESCRIPTION
**Pull request by leojpod**
Attempt to close #9 

So: it seems that "tricking" tailwind into spitting out all the rules via the `safelist` option somehow works! at least it generate stuff and compile :smile: 

however, I've got some timeout issues on the other tests (I've tried to increase the timeout of `ava` but then it's the timeout of the `format` stuff that reject the promise after 10s. 

I believe that with some guidance on what to touch, this could be a working solution to get the v3 support in place :smile:

### CODE REVIEW

**Comment by leojpod** [comment]
Edit: I've changed the timeout on the elm-format command and I've got this: 
image
20min for the documented version :tada:

**Comment by matheus23** [comment]
Thanks so much for this PR :)

I'll take a look at this late this week (hopefully!).

> it's the timeout of the `format` stuff that reject the promise after 10s

Oh god, that sounds like there's really big files generated :sweat_smile:

**Comment by leojpod** [comment]
yeah it's massively big. I wonder if the "safelist" option I'm using isn't a bit overkill... 

perhaps by default the lib could only safelist some stuff (bg, font, text, colors, ...). 
the code I've placed in this PR allows writes up a default safelist if none is given but use the one present in the config if there is one. so it shouldn't be hard to put a message in the CLI that "informs" people about this option if they want more stuff :smile:

**Comment by matheus23** [comment]
Hm. The tests are failing. Do you know what's up with those? @leojpod 

I think it's a cascade of errors that leads to some Elm test application not compiling. What started the cascade seems to be this:
```
(node:1719) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat 'generated in-memory'
```
I'm pretty sure that used to work, I don't understand why that changed :thinking: I guess those are internal changes in postcss/tailwindcssv3. We could probably work around them by writing some temporary files to disk...

**Comment by leojpod** [comment]
@matheus23 do you have the stacktrace?

**Comment by matheus23** [comment]
It's in the GitHub action run for this or. Click "Details" next to the failed run below.

**Comment by leojpod** [comment]
> It's in the GitHub action run for this or. Click "Details" next to the failed run below.

:facepalm: of course :x

**Comment by matheus23** [comment]
I've invited you as a collaborator on this repository so you can just run workflows here without my involvement :v:

**Comment by leojpod** [comment]
Cheers :) let's see if I can get somewhere :)

**Comment by leojpod** [comment]
ok, so the first error might have been coming from the version of JS (somehow?) 

now the tests aren't working but the failure is consistent with the one I observe locally (timeout). 

I was wondering: would it be worth it to run these tests with just a subset of tailwind? (aka override the `safelist` option in the test to only include `bg-*` and `flex.*`), that way it should be a smaller file that gets generated? 

EDIT: that works for the formatted test (I've only included the `bg-`colors and the `text`colors and both tests run under 15s!) 

However, the snapshots version seems to hang forever and nothing is happening. 
Could you give me a quick overview of what theses do and how they work and etc?

**Comment by matheus23** [comment]
Snapshots are generated from an initial run, then they remember the last output. If the output doesn't match what is remembered, then the tests error out.
This is really useful for two reasons: It provides a very "inspectable" test. You can look at the snapshot files yourself to see what's generated. The second reason is refactoring: It allows you to refactor your code while being fairly confident that the output stays the same.

When upgrading tailwindcss or doing other non-refactoring upgrades, the snapshots need to be re-generated. I'm not sure why they're not finishing though, they should just be failing.

**Comment by matheus23** [comment]
For some reason ava would just crash on me when running locally. I've went ahead and upgraded the ava version and regenerated the snapshots. You can see that commit here: 58c621d5af40c9da33090fcc97a28d5a5c57f8c6

**Comment by matheus23** [comment]
> It provides a very "inspectable" test. You can look at the snapshot files yourself to see what's generated.

Unfortunately that's not true in the new ava version anymore :( :man_shrugging:

**Comment by leojpod** [comment]
ok, I've had to commit then uncommit the `.t.md` file generated by the snapshotting since it was too heavy for github. but other than that the tests are green! 

What do you think of it @matheus23 ?

**Review by matheus23 — APPROVED** [review]
Looking good! Thanks for this :tada:

Publishing this soon.

**Comment by leojpod** [comment]
You're welcome :) 

I've started using the v3 at work and it's working without issues so far :)

**Pull request merged**
